/* 합성 자료만 사용해 설정 버튼의 실제 다운로드·파일 선택·미리보기·확정 복원을 검증한다. */
const {chromium,webkit,devices}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=path.join(root,'.local-review','backup-restore');
const server=http.createServer((req,res)=>{
 const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname.replace(/\/$/,'/index.html'));
 if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}
 fs.readFile(file,(error,content)=>{if(error){res.writeHead(404).end();return;}res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.mjs':'application/javascript','.css':'text/css','.png':'image/png','.woff2':'font/woff2'})[path.extname(file)]||'application/octet-stream');res.end(content);});
});
(async()=>{
 fs.mkdirSync(output,{recursive:true});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const engines=[{name:'mobile-chrome',engine:chromium,launch:{headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'},device:devices['Pixel 7']}],results=[],unavailable=[];
 if(fs.existsSync(webkit.executablePath()))engines.push({name:'mobile-webkit',engine:webkit,launch:{headless:true},device:devices['iPhone 13']});else unavailable.push('WebKit 런타임 미설치: 실제 iOS 엔진은 검증하지 못했습니다.');
 for(const engine of engines){
  const browser=await engine.engine.launch(engine.launch);
  try{
   async function check(name,operation){
    const context=await browser.newContext({...engine.device,viewport:{width:390,height:844},acceptDownloads:true,serviceWorkers:'block'}),page=await context.newPage(),errors=[],dialogs=[];let allowConfirm=true;
    page.setDefaultTimeout(10000);page.on('pageerror',error=>errors.push(error.message));page.on('dialog',async dialog=>{dialogs.push({type:dialog.type(),message:dialog.message()});if(dialog.type()==='confirm'&&!allowConfirm)await dialog.dismiss();else await dialog.accept();});
    await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
    try{
     await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:'networkidle'});await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}'});
     const api={page,dialogs,setConfirm:value=>{allowConfirm=value;},
      async settings(){if(await page.locator('#modal-travel-backup').count()&&await page.locator('#modal-travel-backup').evaluate(element=>!element.classList.contains('sheet-closed')))await this.close();if(await page.locator('#modal-settings').evaluate(element=>element.classList.contains('sheet-closed')))await page.locator('header button[onclick="openSettingsModal()"]').first().tap();await page.locator('#tab-settings-data').tap();},
      async close(){await page.locator('#modal-travel-backup').getByRole('button',{name:/닫기|취소/}).first().tap();await page.waitForFunction(()=>document.getElementById('modal-travel-backup').classList.contains('sheet-closed'));},
      async prepare(){await this.settings();await page.locator('#panel-settings-data').getByText('JSON 백업',{exact:true}).tap();await page.waitForFunction(()=>document.getElementById('backup-file-save').getAttribute('href')?.startsWith('blob:'));assert.equal(await page.locator('#backup-file-feedback').getAttribute('role'),'status');},
      async download(){const waiting=page.waitForEvent('download',{timeout:10000});await page.locator('#backup-file-save').tap();const item=await waiting;assert.equal(await item.failure(),null);assert.match(item.suggestedFilename(),/\.json$/);const target=path.join(output,`${engine.name}-${results.length}-backup.json`);await item.saveAs(target);return {buffer:fs.readFileSync(target),name:item.suggestedFilename()};},
      async select(file,valid=true){await this.settings();const waiting=page.waitForEvent('filechooser',{timeout:5000});await page.locator('#panel-settings-data').getByText('JSON 복원',{exact:true}).tap();const chooser=await waiting,element=chooser.element();await chooser.setFiles(file);await page.waitForFunction(element=>element.value==='',element);if(valid){await page.waitForFunction(()=>!document.getElementById('backup-restore-apply').disabled);assert.equal(await page.locator('#modal-travel-backup').isVisible(),true);}else{await page.waitForFunction(()=>document.getElementById('backup-restore-feedback').textContent.trim().length>0);assert.equal(await page.locator('#backup-restore-apply').isEnabled(),false);}},
      async apply(){await page.locator('#backup-restore-apply').tap();await page.waitForFunction(()=>!TravelBackupUI.busy);},
      async state(){return page.evaluate(()=>({trips:State.trips,stored:localStorage.getItem('st_trips_v2')}));},
      file(payload,name='synthetic-backup.json'){return {name,mimeType:'application/json',buffer:Buffer.isBuffer(payload)?payload:Buffer.from(typeof payload==='string'?payload:JSON.stringify(payload),'utf8')};},
      async current(id='current-keep'){await page.evaluate(id=>{const trip=structuredClone(State.trips[0]);trip.id=id;trip.title='복원 전에 지킬 합성 여행';trip.journals[0].text='현재 자료의 원문';State.trips=TripRepository.saveAll([trip]);State.activeTripId=id;renderHub();},id);return this.state();}
     };
     const original=await page.evaluate(async()=>{
      const canvas=document.createElement('canvas');canvas.width=480;canvas.height=240;canvas.getContext('2d').fillStyle='#3d7563';canvas.getContext('2d').fillRect(0,0,480,240);const file=new File([await new Promise(resolve=>canvas.toBlob(resolve))],'synthetic-photo.png',{type:'image/png'}),photo=await SulsulTravel.mediaRepository.prepare(file,{tripId:'backup-ui-synthetic'}),images={photos:[photo.source],photoThumbnails:[photo.thumbnail],mediaIds:[photo.mediaId]};
      const trip={id:'backup-ui-synthetic',title:'백업 UI 검증 <b>가상 여행</b>',startDate:'2030-05-10',endDate:'2030-05-10',timeZone:'Asia/Seoul',countries:['대한민국'],cities:['서울'],currency:'KRW',activeCurrencies:['KRW'],budget:10000,planBlockMeta:{block:{title:'합성 거점',place:'서울',notes:'단순 <b>서식</b><br>줄바꿈 x < y'}},journals:{0:{text:'사진과 함께 보관할 <b>하루 원문</b><br>x < y',...images}},momentEntries:[{id:'backup-moment',date:'2030-05-10',time:'11:00',dayIndex:0,text:'창가에서 본 합성 순간',originalText:'내 원래 순간 문장',...images,coverIndex:0,visibility:'private'}],activityRecords:{'backup-record':{id:'backup-record',text:'일정 기록 원문',...images,coverIndex:0,context:{title:'동네 공원 산책',date:'2030-05-10',time:'10:00'}}},expenses:[{id:'backup-expense',title:'합성 차 한 잔',date:'2030-05-10',amount:3000,currency:'KRW',krw:3000,cat:'food',photos:[photo.source]}],checklist:[],days:[{dayNum:1,date:'2030-05-10',city:'서울',title:'합성 하루',planBlockId:'block',spots:[{id:'backup-spot',title:'동네 공원 산책',desc:'기존 <b>장소 설명</b><br>둘째 줄',time:'10:00',cat:'tour',completed:true,recordId:'backup-record'}]}]};
      State.trips=TripRepository.saveAll([trip]);State.activeTripId=trip.id;renderHub();return State.trips;
     });
     const details=await operation(api,original);assert.deepEqual(errors,[]);results.push({engine:engine.name,name,passed:true,details,errors});
    }catch(error){results.push({engine:engine.name,name,passed:false,error:error.stack||error.message,errors});await page.screenshot({path:path.join(output,`${engine.name}-failure-${results.length}.png`)}).catch(()=>{});}
    finally{await context.close();}
   }
   // 복원은 대기 AI·옛 보조 기록 충돌 방지를 위해 로컬 revision만 올린다.
   const restoredData=trips=>trips.map(({revision,...record})=>record);
   const backup=trips=>({format:'sulsul-backup',schemaVersion:1,version:'test',exportedAt:'2030-01-01T00:00:00.000Z',trips});
   await check('settings 실제 Blob 다운로드와 사진·원문 백업 미리보기/확정 왕복',async(api,original)=>{
    await api.prepare();const widths=[];for(const width of [320,360,390,430]){await api.page.setViewportSize({width,height:844});const geometry=await api.page.locator('#backup-file-save').evaluate(element=>{const box=element.getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth,contained:box.left>=0&&box.right<=innerWidth+1,height:box.height};});assert.equal(geometry.overflow,false);assert.equal(geometry.contained,true);assert.ok(geometry.height>=44);widths.push(width);}await api.page.setViewportSize({width:390,height:844});await api.page.screenshot({path:path.join(output,`${engine.name}-backup-ready.png`)});const exported=await api.download(),payload=JSON.parse(exported.buffer.toString('utf8'));assert.equal(payload.format,'sulsul-backup');assert.equal(payload.schemaVersion,1);assert.deepEqual(payload.trips,original);
    const before=await api.current();await api.select(api.file(exported.buffer));assert.deepEqual(await api.state(),before);assert.equal(api.dialogs.filter(dialog=>dialog.type==='confirm').length,0);assert.ok((await api.page.locator('#backup-restore-summary').textContent()).includes(original[0].title));assert.equal(await api.page.locator('#backup-restore-summary b').count(),0);await api.page.screenshot({path:path.join(output,`${engine.name}-restore-preview.png`)});await api.apply();await api.page.waitForFunction(()=>State.trips[0]?.id==='backup-ui-synthetic');assert.deepEqual(restoredData((await api.state()).trips),restoredData(original));assert.equal(api.dialogs.filter(dialog=>dialog.type==='confirm').length,1);await api.page.reload({waitUntil:'networkidle'});assert.deepEqual(restoredData((await api.state()).trips),restoredData(original));const sizes=await api.page.evaluate(async()=>{const img=new Image();img.src=State.trips[0].journals[0].photos[0];await img.decode();return [img.naturalWidth,img.naturalHeight];});assert.deepEqual(sizes,[480,240]);return {downloadedBlob:true,widths,previewDidNotWrite:true,explicitConfirm:true,photoSize:sizes,originalTextPreserved:true};
   });
   await check('복원 미리보기 취소와 같은 파일 재선택·확인 거절은 현재 문서를 보존',async(api,original)=>{
    const file=api.file(backup(original)),before=await api.current();await api.select(file);await api.close();assert.deepEqual(await api.state(),before);await api.select(file);api.setConfirm(false);await api.apply();assert.deepEqual(await api.state(),before);assert.equal(api.dialogs.filter(dialog=>dialog.type==='confirm').length,1);api.setConfirm(true);await api.select(file);await api.apply();await api.page.waitForFunction(()=>State.trips[0]?.id==='backup-ui-synthetic');assert.deepEqual(restoredData((await api.state()).trips),restoredData(original));return {cancelPreserved:true,declinePreserved:true,sameFileSelectedAgain:true};
   });
   await check('저장 공간 실패는 원본과 보조 기록을 보존하고 같은 미리보기에서 재시도',async(api,original)=>{
    const before=await api.current();await api.page.evaluate(async()=>{await JournalOverflowRepository.save({tripId:'current-keep',dayIndex:0,journal:{text:'실패 시 지킬 보조 원문',photos:[]},revision:7});});await api.select(api.file(backup(original)));await api.page.evaluate(()=>{window.backupOldSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='st_trips_v2')throw new DOMException('quota','QuotaExceededError');return backupOldSetItem.call(this,key,value);};});try{await api.apply();await api.page.waitForFunction(()=>/실패|못|공간/.test(document.getElementById('backup-restore-feedback').textContent));assert.deepEqual(await api.state(),before);assert.equal(await api.page.evaluate(async()=>(await JournalOverflowRepository.loadAll()).length),1);}finally{await api.page.evaluate(()=>{Storage.prototype.setItem=backupOldSetItem;});}assert.equal(await api.page.locator('#backup-restore-apply').isEnabled(),true);await api.apply();await api.page.waitForFunction(()=>State.trips[0]?.id==='backup-ui-synthetic');assert.deepEqual(restoredData((await api.state()).trips),restoredData(original));assert.equal(await api.page.evaluate(async()=>(await JournalOverflowRepository.loadAll()).length),0);return {failedApplyAtomic:true,overflowNotClearedOnFailure:true,retrySaved:true};
   });
   const invalids=[['손상 JSON','{not-json'],['미래 백업 계약',{format:'sulsul-backup',schemaVersion:99,trips:[]}],['빈 객체',{}],['null 여행',{format:'sulsul-backup',schemaVersion:1,trips:[null]}],['잘못된 여행 형식',{format:'sulsul-backup',schemaVersion:1,trips:[{id:'broken',title:'형식 오류',days:'bad'}]}]];
   for(const [name,payload]of invalids)await check(`${name} 파일은 실제 파일 선택 뒤에도 현재 자료 유지`,async(api)=>{const before=await api.state();await api.select(api.file(payload),false);assert.deepEqual(await api.state(),before);assert.equal(api.dialogs.filter(dialog=>dialog.type==='confirm').length,0);return {rejectedBeforeApply:true,currentDocumentUnchanged:true};});
   await check('활성 HTML은 거절하고 미리보기 DOM에서 실행되지 않는다',async(api,original)=>{const trips=structuredClone(original);trips[0].planBlockMeta.block.notes='<img data-backup-probe="1" src="x" onerror="window.backupProbe=1">';const before=await api.state();await api.select(api.file(backup(trips)),false);assert.deepEqual(await api.state(),before);assert.equal(await api.page.locator('[data-backup-probe]').count(),0);assert.equal(await api.page.evaluate(()=>window.backupProbe),undefined);return {activeHtmlRejected:true,noDomInjection:true};});
   await check('50MB 초과 실제 합성 파일은 읽기/교체 없이 거절',async(api)=>{const target=path.join(output,`${engine.name}-oversize-synthetic.json`);fs.writeFileSync(target,Buffer.alloc(50*1024*1024+1,32));try{const before=await api.state();await api.select(target,false);assert.deepEqual(await api.state(),before);assert.match(await api.page.locator('#backup-restore-feedback').textContent(),/50|용량|크기|이하/);return {oversizeRejected:true,currentDocumentUnchanged:true};}finally{fs.unlinkSync(target);}});
   await check('BOM을 포함한 구 version/trips 백업의 별칭과 원문을 보완해 복원',async(api)=>{
    const legacy={id:'legacy-backup-ui',name:'구 파일의 합성 여행',startDate:'2030.05.10',currency:'KRW',activeCurrencies:['KRW'],cities:['New York'],countries:['미국'],planBlockMeta:{legacy:{place:'New York',notes:'x < y'}},days:[{day:1,date:'2030년 5월 10일',city:'New York',planBlockId:'legacy',timeline:[{name:'구 일정 제목',description:'기존 <b>설명</b><br>둘째 줄',time:'09:00',category:'tour'}]}],journals:{0:{content:'구 회고 <b>원문</b><br>x < y',photos:[]}},expenses:[]},file=api.file('\ufeff'+JSON.stringify({version:'1.7.0',trips:[legacy]}));const before=await api.state();await api.select(file);assert.deepEqual(await api.state(),before);await api.apply();await api.page.waitForFunction(()=>State.trips[0]?.id==='legacy-backup-ui');const trip=(await api.state()).trips[0];assert.equal(trip.title,legacy.name);assert.equal(trip.name,legacy.name);assert.equal(trip.days[0].date,'2030-05-10');assert.equal(trip.days[0].spots[0].title,'구 일정 제목');assert.equal(trip.days[0].spots[0].desc,legacy.days[0].timeline[0].description);for(const [key,value] of Object.entries(legacy.days[0].timeline[0]))assert.deepEqual(trip.days[0].timeline[0][key],value);assert.equal(trip.journals[0].text,legacy.journals[0].content);return {bomSupported:true,legacyAliasesNormalized:true,originalsPreserved:true};
   });
   await check('빈 여행 목록도 명시 적용 확인 뒤에만 교체한다',async(api)=>{const before=await api.state();await api.select(api.file(backup([])));assert.deepEqual(await api.state(),before);assert.equal(api.dialogs.length,0);await api.apply();await api.page.waitForFunction(()=>State.trips.length===0);assert.deepEqual((await api.state()).trips,[]);assert.deepEqual(JSON.parse((await api.state()).stored),[]);assert.equal(api.dialogs.filter(dialog=>dialog.type==='confirm').length,1);await api.page.reload({waitUntil:'networkidle'});assert.deepEqual((await api.state()).trips,[]);return {emptyListExplicitlyConfirmed:true,noAutoSeed:true};});
   await check('전체 백업은 IndexedDB의 최신 보조 원문을 합쳐 실제 파일에 담는다',async(api,original)=>{await api.page.evaluate(async()=>{await JournalOverflowRepository.save({tripId:'backup-ui-synthetic',dayIndex:0,journal:{text:'IndexedDB에 남은 최신 합성 회고',photos:State.trips[0].journals[0].photos},revision:9});});const before=await api.state();await api.prepare();const exported=await api.download(),payload=JSON.parse(exported.buffer.toString('utf8'));assert.equal(payload.trips[0].journals[0].text,'IndexedDB에 남은 최신 합성 회고');assert.deepEqual(payload.trips[0].journals[0].photos,original[0].journals[0].photos);assert.deepEqual(await api.state(),before);return {latestOverflowExported:true,photosRetained:true,exportDidNotMutate:true};});
   await check('여러 날의 보조 글과 보관 사진은 백업 및 재접속에서 순서와 무관하게 보존',async(api,original)=>{
    await api.page.evaluate(async()=>{
     const trip=State.trips[0];trip.revision=3;trip.days.push({...structuredClone(trip.days[0]),id:'backup-day-2',dayNum:2,date:'2030-05-11',spots:[]});trip.journals[1]={text:'이전 둘째날',photos:[],mediaIds:trip.journals[0].mediaIds};State.trips=TripRepository.saveAll(State.trips);
     await JournalOverflowRepository.save({tripId:trip.id,dayIndex:0,revision:5,journal:{text:'최신 첫날 보조 글'}});
     await JournalOverflowRepository.save({tripId:trip.id,dayIndex:1,revision:4,journal:{text:'최신 둘째날 보조 글'}});
    });
    await api.prepare();const payload=JSON.parse((await api.download()).buffer.toString('utf8'));
    assert.equal(payload.trips[0].journals[0].text,'최신 첫날 보조 글');assert.equal(payload.trips[0].journals[1].text,'최신 둘째날 보조 글');assert.deepEqual(payload.trips[0].journals[1].photos,original[0].journals[0].photos);
    await api.page.reload({waitUntil:'networkidle'});await api.page.waitForFunction(()=>State.trips[0].journals[0].text==='최신 첫날 보조 글');const restored=(await api.state()).trips[0];assert.equal(restored.journals[1].text,'최신 둘째날 보조 글');assert.equal(restored.revision,5);return {bothDatesExported:true,overflowBlobIncluded:true,bothDatesRestoredOnStartup:true};
   });
   await check('복원 후 보조 기록 정리가 실패해도 높은 revision으로 옛 원문의 부활을 막는다',async(api,original)=>{
    await api.page.evaluate(async()=>{await JournalOverflowRepository.save({tripId:'backup-ui-synthetic',dayIndex:0,journal:{text:'복원 뒤 되살아나면 안 되는 옛 합성 원문',photos:[]},revision:55});window.backupOldClear=JournalOverflowRepository.clearAll;JournalOverflowRepository.clearAll=async()=>{throw new Error('synthetic-clear-failure');};});await api.select(api.file(backup(original)));try{await api.apply();await api.page.waitForFunction(()=>State.trips[0].revision>55);assert.equal((await api.state()).trips[0].journals[0].text,original[0].journals[0].text);assert.equal(await api.page.evaluate(async()=>(await JournalOverflowRepository.loadAll()).length),1);}finally{await api.page.evaluate(()=>{JournalOverflowRepository.clearAll=backupOldClear;});}await api.page.reload({waitUntil:'networkidle'});assert.equal((await api.state()).trips[0].journals[0].text,original[0].journals[0].text);assert.ok((await api.state()).trips[0].revision>55);return {restoreCommitted:true,staleOverflowStillPresent:true,revisionProtected:true,reloadPreserved:true};
   });
   await check('손상된 기기 문서는 원문을 보존하고 명시 확인한 정상 백업으로 복구',async(api,original)=>{
    const broken='{"trips":';await api.page.evaluate(raw=>localStorage.setItem('st_trips_v2',raw),broken);await api.page.reload({waitUntil:'networkidle'});
    const recovery=await api.page.evaluate(()=>State.storageRecovery);assert.ok(recovery.backupKey);assert.equal(await api.page.evaluate(key=>localStorage.getItem(key),recovery.backupKey),broken);
    await api.select(api.file(backup(original)));api.setConfirm(false);await api.apply();assert.equal((await api.state()).stored,broken);assert.deepEqual((await api.state()).trips,[]);
    api.setConfirm(true);await api.apply();await api.page.waitForFunction(()=>State.trips[0]?.id==='backup-ui-synthetic');assert.equal(await api.page.evaluate(()=>State.storageRecovery),null);assert.equal(await api.page.evaluate(key=>localStorage.getItem(key),recovery.backupKey),broken);assert.deepEqual(restoredData((await api.state()).trips),restoredData(original));await api.page.reload({waitUntil:'networkidle'});assert.deepEqual(restoredData((await api.state()).trips),restoredData(original));return {corruptOriginalPreserved:true,declineDidNotWrite:true,confirmedRecoverySaved:true};
   });
   await check('잘못된 배열의 손상 원문 보관이 실패하면 복원을 중단하고 보관 성공 후 재시도',async(api,original)=>{
    const raw='[null]';await api.page.evaluate(raw=>localStorage.setItem('st_trips_v2',raw),raw);
    await api.page.addInitScript(()=>{window.backupCorruptSet=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.startsWith('st_trips_v2_corrupt_'))throw new DOMException('synthetic preservation quota','QuotaExceededError');return backupCorruptSet.call(this,key,value);};});
    await api.page.reload({waitUntil:'networkidle'});assert.ok(await api.page.evaluate(()=>State.storageRecovery));
    await api.select(api.file(backup(original)));await api.apply();assert.equal((await api.state()).stored,raw);assert.deepEqual((await api.state()).trips,[]);assert.equal(await api.page.locator('#backup-restore-apply').isEnabled(),true);
    await api.page.evaluate(()=>{Storage.prototype.setItem=backupCorruptSet;});await api.apply();await api.page.waitForFunction(()=>State.trips[0]?.id==='backup-ui-synthetic');assert.deepEqual(restoredData((await api.state()).trips),restoredData(original));assert.equal(await api.page.evaluate(raw=>Object.keys(localStorage).some(key=>key.startsWith('st_trips_v2_corrupt_')&&localStorage.getItem(key)===raw),raw),true);return {invalidArrayNotReplacedWithoutPreservation:true,originalKept:true,retrySaved:true};
   });
   await check('검토 중 현재 여행이 바뀌면 오래된 미리보기 적용을 중단',async(api,original)=>{
    await api.select(api.file(backup(original)));await api.page.evaluate(()=>{State.trips[0].journals[0].text='미리보기 이후 직접 수정한 원문';saveTrips();});const changed=await api.state();await api.apply();await api.page.waitForFunction(()=>document.getElementById('backup-restore-feedback').textContent.includes('변경'));assert.deepEqual(await api.state(),changed);assert.equal(api.dialogs.length,0);return {stalePreviewBlocked:true,newWritingPreserved:true};
   });
   await check('사진 사본이 빠졌어도 같은 여행의 보관 Blob을 백업 파일에 복구',async(api,original)=>{
    await api.page.evaluate(()=>{State.trips[0].journals[0].photos=[];State.trips=TripRepository.saveAll(State.trips);renderHub();});const before=await api.state();await api.prepare();const exported=await api.download(),payload=JSON.parse(exported.buffer.toString('utf8'));assert.deepEqual(payload.trips[0].journals[0].photos,original[0].journals[0].photos);assert.deepEqual(await api.state(),before);return {archivedPhotoIncluded:true,currentDocumentNotMutated:true};
   });
   await check('준비된 파일 공유는 실제 버튼 클릭에서만 호출하고 취소 후 다운로드 가능',async(api,original)=>{
    await api.page.evaluate(()=>{window.backupShareCalls=[];Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async payload=>{backupShareCalls.push({name:payload.files[0].name,text:await payload.files[0].text(),userGesture:navigator.userActivation.isActive});throw new DOMException('synthetic cancel','AbortError');}});});await api.prepare();assert.equal(await api.page.evaluate(()=>backupShareCalls.length),0);await api.page.locator('#backup-file-share').tap();await api.page.waitForFunction(()=>backupShareCalls.length===1);const shared=await api.page.evaluate(()=>backupShareCalls[0]);assert.match(shared.name,/\.json$/);assert.deepEqual(JSON.parse(shared.text).trips,original);assert.equal(shared.userGesture,true);assert.deepEqual(restoredData((await api.state()).trips),restoredData(original));const exported=await api.download();assert.deepEqual(JSON.parse(exported.buffer.toString('utf8')).trips,original);return {shareCalledAfterGesture:true,shareCancelledSafely:true,downloadFallbackWorks:true};
   });
  }finally{await browser.close();}
 }
 console.log(JSON.stringify({passed:results.every(result=>result.passed),results,unavailable},null,2));assert.ok(results.every(result=>result.passed),'실제 백업·복원 UI 회귀 실패');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>server.close());
