/* 가상 예제의 명시적 추가·삭제와 최초 방문 개인정보 경계를 실제 HTTP 브라우저에서 검증한다. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const LZString=require('../vendor/lz-string/lz-string.min.js');
const root=path.resolve(__dirname,'..'),output=path.join(root,'.local-review','demo-onboarding');
const server=http.createServer((req,res)=>{
 const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname.replace(/\/$/,'/index.html'));
 if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}
 fs.readFile(file,(error,content)=>{if(error){res.writeHead(404).end();return;}res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.mjs':'application/javascript','.css':'text/css','.png':'image/png','.woff2':'font/woff2'})[path.extname(file)]||'application/octet-stream');res.end(content);});
});
// 초기화가 자동 보완하는 표시용 필드도 명시해 삭제 전후 전체 문서를 비교한다.
const syntheticTrip=(id,title)=>({id,title,startDate:'2030-05-10',endDate:'2030-05-10',timeZone:'Asia/Seoul',countries:['대한민국'],cities:['서울'],currency:'KRW',activeCurrencies:['KRW'],budget:0,journals:{},momentEntries:[],activityRecords:{},expenses:[],checklist:[],planBlockMeta:{[`block-${id}`]:{title:'내 거점',place:'서울',notes:'합성 계획 메모'}},days:[{dayNum:1,date:'2030-05-10',city:'서울',title:'내가 정한 하루',planBlockId:`block-${id}`,spots:[{id:'private-spot',title:'동네 공원 산책',time:'10:00',completed:false}]}]});
(async()=>{
 fs.mkdirSync(output,{recursive:true});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})}),results=[],errors=[];
 async function check(name,options,operation){
  const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Seoul',serviceWorkers:'block'}),page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',error=>errors.push({name,error:error.message}));
  await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
  await page.addInitScript(({storage,confirm})=>{
   // 새로고침에서 합성 구버전 자료를 다시 넣지 않아 실제 일회성 마이그레이션을 검사한다.
   if(!sessionStorage.getItem('demo-test-initialized')){Object.entries(storage).forEach(([key,value])=>localStorage.setItem(key,value));sessionStorage.setItem('demo-test-initialized','true');}
   window.alert=()=>{};window.confirm=()=>confirm;
  },{storage:options.storage||{},confirm:options.confirm!==false});
  try{await page.goto(`http://127.0.0.1:${server.address().port}/${options.search||''}${options.hash||''}`,{waitUntil:'networkidle'});await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}'});const details=await operation(page);results.push({name,passed:true,details});}
  catch(error){results.push({name,passed:false,error:error.stack||error.message});await page.screenshot({path:path.join(output,`failure-${results.length}.png`)}).catch(()=>{});}
  finally{await context.close();}
 }
 async function confirmTripDeletion(page,id){await page.evaluate(id=>requestDeleteTrip(id),id);await page.waitForTimeout(400);await page.locator('#confirm-delete-btn').click();}
 try{
  await check('최초 빈 방문은 여행을 만들지 않고 선택 제안만 표시한다',{},async page=>{
   assert.deepEqual(await page.evaluate(()=>State.trips),[]);assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('st_trips_v2')||'[]')),[]);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),true);
   const sizes=[];for(const width of [320,360,390,430]){await page.setViewportSize({width,height:844});const geometry=await page.evaluate(()=>{const offer=document.getElementById('demo-onboarding-offer').getBoundingClientRect();return {width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth,contained:offer.left>=0&&offer.right<=innerWidth+1};});assert.deepEqual(geometry,{width,overflow:false,contained:true});sizes.push(width);}
   await page.screenshot({path:path.join(output,'first-visit-offer.png')});await page.locator('#demo-onboarding-offer [onclick="dismissDemoOffer()"]').click();assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),false);await page.reload({waitUntil:'networkidle'});assert.deepEqual(await page.evaluate(()=>State.trips),[]);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),false);return {automaticTrips:0,widths:sizes,dismissedAfterReload:true};
  });
  await check('가상 예제 명시 추가·중복 방지·사본 및 동일 제목 개인 여행 보존',{},async page=>{
   await page.locator('#demo-onboarding-offer [onclick*="addDemoTrip"]').click();const added=await page.evaluate(()=>State.trips);assert.equal(added.length,1);assert.equal(added[0].isSample,true);assert.equal(added[0].days.length,5);assert.ok(added[0].cities.includes('타이베이'));assert.ok(added[0].cities.includes('타이중'));assert.ok((added[0].expenses||[]).every(expense=>expense.title.includes('[가상 지출]')));assert.ok(Object.values(added[0].journals||{}).every(journal=>journal.text.includes('[가상 하루 회고]')));assert.ok((added[0].momentEntries||[]).every(moment=>moment.text.includes('[가상 순간 기록]')));assert.ok(Object.values(added[0].activityRecords||{}).every(record=>record.text.includes('[가상 일정 기록]')));assert.doesNotMatch(JSON.stringify(added),/실제 항공권|AC062|AC194|LA2024|8,650,000/);
   await page.evaluate(()=>{addDemoTrip();addDemoTrip();});assert.equal(await page.evaluate(()=>State.trips.length),1);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),false);
   const preserved=await page.evaluate(()=>{
    const demo=State.trips.find(trip=>trip.isSample);duplicateTrip(demo.id);const copy=State.trips.find(trip=>trip.id!==demo.id);window.demoCopyId=copy.id;const personal=structuredClone(demo);personal.id='personal-same-demo-title';delete personal.isSample;personal.journals={0:{text:'같은 제목이어도 내 기록',photos:[]}};State.trips=TripRepository.saveAll([...State.trips,personal]);return {copyId:copy.id,copyIsSample:Object.hasOwn(copy,'isSample'),title:personal.title};
   });assert.equal(preserved.copyIsSample,false);
   await page.evaluate(()=>openSettingsModal('data'));assert.equal(await page.locator('#demo-settings-status').isVisible(),true);
   for(const width of [320,360,390,430]){await page.setViewportSize({width,height:844});const geometry=await page.evaluate(()=>{const sheet=document.querySelector('#modal-settings .sheet-box').getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth,contained:sheet.left>=0&&sheet.right<=innerWidth+1};});assert.deepEqual(geometry,{overflow:false,contained:true});}
   await page.locator('#modal-settings [onclick*="deleteDemoTrips"]').click();const remaining=await page.evaluate(()=>State.trips.map(trip=>({id:trip.id,sample:!!trip.isSample})));assert.deepEqual(remaining,[{id:preserved.copyId,sample:false},{id:'personal-same-demo-title',sample:false}]);
   await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>State.trips.filter(trip=>trip.isSample).length),0);assert.equal(await page.evaluate(()=>State.trips.find(trip=>trip.id==='personal-same-demo-title').journals[0].text),'같은 제목이어도 내 기록');assert.ok(await page.evaluate(id=>State.trips.some(trip=>trip.id===id),preserved.copyId));assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),false);return {demoDays:5,duplicatePrevented:true,personalIds:remaining.map(trip=>trip.id),deletedAfterReload:true};
  });
  await check('일반 여행 카드로 마지막 예제를 삭제해도 다시 생성되지 않는다',{},async page=>{
   await page.locator('#demo-onboarding-offer [onclick*="addDemoTrip"]').click();const id=await page.evaluate(()=>State.trips[0].id);await confirmTripDeletion(page,id);assert.deepEqual(await page.evaluate(()=>State.trips),[]);assert.equal(await page.evaluate(()=>State.activeTripId),null);await page.reload({waitUntil:'networkidle'});assert.deepEqual(await page.evaluate(()=>State.trips),[]);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),false);return {lastTripDeletionPersisted:true};
  });
  await check('예제 추가 저장 실패는 문서와 제안을 보존하며 재시도가 가능하다',{},async page=>{
   const failed=await page.evaluate(()=>{
    const before=JSON.stringify(State.trips),stored=localStorage.getItem('st_trips_v2'),keys=Object.fromEntries(Object.keys(localStorage).map(key=>[key,localStorage.getItem(key)])),old=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='st_trips_v2')throw new DOMException('quota','QuotaExceededError');return old.call(this,key,value);};try{addDemoTrip();}finally{Storage.prototype.setItem=old;}return {memory:JSON.stringify(State.trips)===before,persisted:localStorage.getItem('st_trips_v2')===stored,allStorage:JSON.stringify(Object.fromEntries(Object.keys(localStorage).map(key=>[key,localStorage.getItem(key)])))===JSON.stringify(keys)};
   });assert.deepEqual(failed,{memory:true,persisted:true,allStorage:true});assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),true);await page.locator('#demo-onboarding-offer [onclick*="addDemoTrip"]').click();assert.equal(await page.evaluate(()=>State.trips.filter(trip=>trip.isSample).length),1);await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>State.trips.filter(trip=>trip.isSample).length),1);return {failureAtomic:true,retrySaved:true};
  });
  await check('설정 예제 삭제 저장 실패는 원본과 삭제 표식을 보존한다',{},async page=>{
   await page.locator('#demo-onboarding-offer [onclick*="addDemoTrip"]').click();const failed=await page.evaluate(()=>{
    const before=JSON.stringify(State.trips),stored=localStorage.getItem('st_trips_v2'),keys=Object.fromEntries(Object.keys(localStorage).map(key=>[key,localStorage.getItem(key)])),old=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='st_trips_v2')throw new DOMException('quota','QuotaExceededError');return old.call(this,key,value);};try{deleteDemoTrips();}finally{Storage.prototype.setItem=old;}return {memory:JSON.stringify(State.trips)===before,persisted:localStorage.getItem('st_trips_v2')===stored,allStorage:JSON.stringify(Object.fromEntries(Object.keys(localStorage).map(key=>[key,localStorage.getItem(key)])))===JSON.stringify(keys)};
   });assert.deepEqual(failed,{memory:true,persisted:true,allStorage:true});await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>State.trips.filter(trip=>trip.isSample).length),1);await page.evaluate(()=>deleteDemoTrips());assert.deepEqual(await page.evaluate(()=>State.trips),[]);await page.reload({waitUntil:'networkidle'});assert.deepEqual(await page.evaluate(()=>State.trips),[]);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),false);return {failureAtomic:true,retryDeleted:true};
  });
  const shared=syntheticTrip('shared-source','친구가 보낸 가상 여행'),payload={format:'sulsul-trip',schemaVersion:1,shareId:'demo-onboarding-share',scope:{journals:false,finances:false},trip:shared},hash='#share='+LZString.compressToEncodedURIComponent(JSON.stringify(payload));
  await check('공유 링크 첫 방문은 승인한 사본 하나만 추가한다',{hash},async page=>{
   const trips=await page.evaluate(()=>State.trips);assert.equal(trips.length,1);assert.equal(trips[0].importedShareId,'demo-onboarding-share');assert.ok(trips[0].title.startsWith(shared.title));assert.equal(!!trips[0].isSample,false);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),false);await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>State.trips.length),1);return {importedTrips:1,automaticDemo:false};
  });
  await check('공유 링크 거절은 원본 URL과 빈 여행 목록을 유지한다',{hash,confirm:false},async page=>{
   assert.deepEqual(await page.evaluate(()=>State.trips),[]);assert.ok(await page.evaluate(()=>location.hash.startsWith('#share=')));assert.equal(await page.evaluate(()=>State.trips.some(trip=>trip.isSample)),false);assert.equal(await page.locator('#snapshot-entry-notice').isVisible(),true);assert.match(await page.locator('#snapshot-entry-notice').textContent(),/공유 당시/);await page.locator('#snapshot-open-app').click();await page.waitForFunction(()=>location.hash==='');assert.deepEqual(await page.evaluate(()=>State.trips),[]);assert.equal(await page.locator('#snapshot-entry-notice').isVisible(),false);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),true);return {declinedWithoutSeed:true,returnedToBaseApp:true};
  });
  const privateSharedVisitor=syntheticTrip('private-share-visitor','공유받은 링크와 별개인 내 여행');privateSharedVisitor.journals={0:{text:'이 기기에만 보관한 내 원문',photos:[]}};
  await check('공유 링크 거절 후 기본 앱으로 돌아가도 개인 저장 자료는 유지한다',{hash,search:'?entry=synthetic-snapshot',confirm:false,storage:{st_trips_v2:JSON.stringify([privateSharedVisitor])}},async page=>{
   const before=await page.evaluate(()=>({trips:State.trips,stored:localStorage.getItem('st_trips_v2')}));assert.equal(before.trips.length,1);assert.equal(before.trips[0].id,privateSharedVisitor.id);assert.ok(await page.evaluate(()=>location.hash.startsWith('#share=')));assert.equal(await page.locator('#snapshot-entry-notice').isVisible(),true);assert.match(await page.locator('#snapshot-entry-notice').textContent(),/공유 당시/);await page.locator('#snapshot-open-app').click();await page.waitForFunction(()=>location.hash===''&&location.search==='');assert.equal(await page.evaluate(()=>State.currentView),'hub');assert.deepEqual(await page.evaluate(()=>State.trips),before.trips);assert.equal(await page.evaluate(()=>localStorage.getItem('st_trips_v2')),before.stored);assert.equal(await page.locator('#snapshot-entry-notice').isVisible(),false);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),false);await page.reload({waitUntil:'networkidle'});assert.deepEqual(await page.evaluate(()=>State.trips),before.trips);return {privateOriginalPreserved:true,queryAndHashRemoved:true,noSnapshotImported:true};
  });
  const legacy=syntheticTrip('legacy-private','내 이전 버전 여행');legacy.journals={0:{text:'구버전 원문 보존',photos:[]}};
  await check('구버전 개인 여행은 한 번만 마이그레이션하고 삭제 후 재수입하지 않는다',{storage:{st_current_trip:JSON.stringify(legacy)}},async page=>{
   const trips=await page.evaluate(()=>State.trips);assert.equal(trips.length,1);assert.equal(trips[0].id,legacy.id);assert.equal(trips[0].journals[0].text,'구버전 원문 보존');assert.equal(!!trips[0].isSample,false);await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>State.trips.length),1);await confirmTripDeletion(page,legacy.id);assert.deepEqual(await page.evaluate(()=>State.trips),[]);await page.reload({waitUntil:'networkidle'});assert.deepEqual(await page.evaluate(()=>State.trips),[]);return {legacyPreserved:true,migratedOnce:true,noResurrection:true};
  });
  const retired=syntheticTrip('trip_sa_showcase_22d','기존 기기에만 보관된 내 남미 계획');retired.isSample=true;retired.journals={0:{text:'내가 편집한 기존 기록',photos:[]}};
  await check('기존 기기의 구 예제 편집본은 개인 계획으로 보존하며 예제 삭제에서 제외한다',{storage:{st_trips_v2:JSON.stringify([retired])}},async page=>{
   const before=await page.evaluate(()=>State.trips);assert.equal(before.length,1);assert.equal(before[0].id,retired.id);assert.equal(await page.evaluate(()=>isRetiredBuiltInTrip(State.trips[0])),true);assert.equal(before[0].journals[0].text,'내가 편집한 기존 기록');await page.evaluate(()=>deleteDemoTrips());assert.deepEqual(await page.evaluate(()=>State.trips),before);await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>State.trips[0].journals[0].text),'내가 편집한 기존 기록');return {existingUserDataPreserved:true,notDeletedAsNewDemo:true};
  });
  const retired21=syntheticTrip('trip_sa_showcase_21d',retired.title);retired21.legacyExampleRetired=true;retired21.journals={0:{text:'21일 초안에 남긴 합성 원문',photos:[]}};
  const sameRetiredTitle=syntheticTrip('personal-retired-title',retired.title);sameRetiredTitle.journals={0:{text:'같은 제목의 개인 원문',photos:[]}};
  const copiedRetired=syntheticTrip('personal-retired-copy',retired.title+' (사본)');copiedRetired.legacyExampleRetired=true;copiedRetired.journals={0:{text:'기존 초안에서 복사한 내 원문',photos:[]}};
  await check('기존 자동 초안 안내와 선택 삭제는 거절·저장 실패·다른 여행 보존을 지킨다',{storage:{st_trips_v2:JSON.stringify([retired,retired21,sameRetiredTitle,copiedRetired])}},async page=>{
   const before=await page.evaluate(()=>State.trips);assert.equal(before.length,4);assert.deepEqual(await page.evaluate(()=>State.trips.filter(isRetiredBuiltInTrip).map(trip=>trip.id).sort()),['trip_sa_showcase_21d','trip_sa_showcase_22d']);assert.equal(await page.locator('#legacy-demo-hub-notice').isVisible(),true);
   async function checkNotice(selector){const widths=[];for(const width of [320,360,390,430]){await page.setViewportSize({width,height:844});const geometry=await page.locator(selector).evaluate(element=>{const box=element.getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth,contained:box.left>=0&&box.right<=innerWidth+1};});assert.deepEqual(geometry,{overflow:false,contained:true});widths.push(width);}return widths;}
   const widths=await checkNotice('#legacy-demo-hub-notice');await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'retired-hub-notice.png')});await page.evaluate(id=>openTripWorkspace(id),retired.id);assert.equal(await page.locator('#legacy-demo-workspace-notice').isVisible(),true);await checkNotice('#legacy-demo-workspace-notice');await page.evaluate(()=>openLegacyDemoManager());assert.equal(await page.locator('#legacy-demo-settings').isVisible(),true);await checkNotice('#legacy-demo-settings');await page.setViewportSize({width:390,height:844});await page.locator('#legacy-demo-settings').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'retired-settings.png')});
   const list=page.locator('#legacy-demo-list');assert.equal(await list.locator('[data-retired-delete]').count(),2);assert.equal(await list.locator('[data-retired-delete="personal-retired-title"]').count(),0);assert.equal(await list.locator('[data-retired-delete="personal-retired-copy"]').count(),0);const firstId=await list.locator('[data-retired-delete]').first().getAttribute('data-retired-delete');assert.equal(await list.getByRole('button',{name:/확인|보기/}).count(),2);await list.getByRole('button',{name:/확인|보기/}).first().click();assert.equal(await page.evaluate(()=>State.activeTripId),firstId);await page.evaluate(()=>openLegacyDemoManager());
   await page.evaluate(()=>{window.retiredBefore=JSON.stringify(State.trips);window.retiredStored=localStorage.getItem('st_trips_v2');window.confirm=()=>false;});await page.locator(`[data-retired-delete="${retired.id}"]`).click();assert.deepEqual(await page.evaluate(()=>({memory:JSON.stringify(State.trips)===retiredBefore,persisted:localStorage.getItem('st_trips_v2')===retiredStored})),{memory:true,persisted:true});
   await page.evaluate(()=>{window.confirm=()=>true;window.retiredStorageBefore=Object.fromEntries(Object.keys(localStorage).map(key=>[key,localStorage.getItem(key)]));window.retiredOriginalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='st_trips_v2')throw new DOMException('quota','QuotaExceededError');return retiredOriginalSetItem.call(this,key,value);};});try{await page.locator(`[data-retired-delete="${retired.id}"]`).click();}finally{await page.evaluate(()=>{Storage.prototype.setItem=retiredOriginalSetItem;});}
   assert.deepEqual(await page.evaluate(()=>({memory:JSON.stringify(State.trips)===retiredBefore,persisted:localStorage.getItem('st_trips_v2')===retiredStored,allStorage:JSON.stringify(Object.fromEntries(Object.keys(localStorage).map(key=>[key,localStorage.getItem(key)])))===JSON.stringify(retiredStorageBefore)})),{memory:true,persisted:true,allStorage:true});assert.equal(await page.locator(`[data-retired-delete="${retired.id}"]`).count(),1);
   await page.locator(`[data-retired-delete="${retired.id}"]`).click();const after=await page.evaluate(()=>State.trips);assert.equal(after.length,3);assert.equal(after.some(trip=>trip.id===retired.id),false);for(const trip of before.filter(trip=>trip.id!==retired.id))assert.deepEqual(after.find(item=>item.id===trip.id),trip);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),false);
   await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(id=>State.trips.some(trip=>trip.id===id),retired.id),false);assert.equal(await page.locator('#legacy-demo-hub-notice').isVisible(),true);await page.evaluate(()=>openLegacyDemoManager());assert.equal(await page.locator('#legacy-demo-list [data-retired-delete]').count(),1);await page.locator(`[data-retired-delete="${retired21.id}"]`).click();const personal=await page.evaluate(()=>State.trips);assert.equal(personal.length,2);assert.deepEqual(personal.map(trip=>trip.id).sort(),[sameRetiredTitle.id,copiedRetired.id].sort());assert.equal(await page.locator('#legacy-demo-hub-notice').isVisible(),false);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),false);await page.reload({waitUntil:'networkidle'});for(const trip of personal)assert.deepEqual(await page.evaluate(id=>State.trips.find(trip=>trip.id===id),trip.id),trip);return {retiredIdsOnly:true,widths,declineAtomic:true,quotaAtomic:true,deletedOneAtATime:true,personalAndCopyPreserved:true};
  });
  await check('마지막 기존 자동 초안 선택 삭제는 새 가상 예제 제안을 다시 표시한다',{storage:{st_trips_v2:JSON.stringify([retired]),st_demo_choice_v1:'dismissed'}},async page=>{
   assert.equal(await page.locator('#legacy-demo-hub-notice').isVisible(),true);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),false);await page.evaluate(()=>openLegacyDemoManager());await page.locator(`[data-retired-delete="${retired.id}"]`).click();assert.deepEqual(await page.evaluate(()=>State.trips),[]);assert.equal(await page.locator('#legacy-demo-hub-notice').isVisible(),false);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),true);await page.reload({waitUntil:'networkidle'});assert.deepEqual(await page.evaluate(()=>State.trips),[]);assert.equal(await page.locator('#demo-onboarding-offer').isVisible(),true);await page.locator('#demo-onboarding-offer [onclick*="addDemoTrip"]').click();assert.deepEqual(await page.evaluate(()=>({count:State.trips.length,days:State.trips[0].days.length,newDemo:!!State.trips[0].isSample,retired:isRetiredBuiltInTrip(State.trips[0])})),{count:1,days:5,newDemo:true,retired:false});await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(id=>State.trips.some(trip=>trip.id===id),retired.id),false);return {oldDraftGoneAfterReload:true,newOfferShown:true,newVirtualDemoAdded:true};
  });
  const privateFixedId=syntheticTrip('trip_sa_showcase_22d',retired.title);privateFixedId.isSample=false;privateFixedId.legacyExampleRetired=false;privateFixedId.journals={0:{text:'같은 식별자지만 표식 없는 개인 원문',photos:[]}};
  await check('구 고정 ID만 같은 개인 여행은 기존 자동 초안으로 삭제하지 않는다',{storage:{st_trips_v2:JSON.stringify([privateFixedId])}},async page=>{
   const before=await page.evaluate(()=>({trips:State.trips,stored:localStorage.getItem('st_trips_v2')}));assert.equal(await page.evaluate(()=>isRetiredBuiltInTrip(State.trips[0])),false);assert.equal(await page.locator('#legacy-demo-hub-notice').isVisible(),false);await page.evaluate(()=>openLegacyDemoManager());assert.equal(await page.locator('#legacy-demo-list [data-retired-delete]').count(),0);await page.evaluate(id=>deleteRetiredBuiltInTrip(id),privateFixedId.id);assert.deepEqual(await page.evaluate(()=>State.trips),before.trips);assert.equal(await page.evaluate(()=>localStorage.getItem('st_trips_v2')),before.stored);await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>State.trips[0].journals[0].text),'같은 식별자지만 표식 없는 개인 원문');return {unmarkedFixedIdProtected:true};
  });
  await check('중복된 구 식별자는 개인 표식과 무관하게 확인 없이 삭제를 중단한다',{storage:{st_trips_v2:JSON.stringify([retired,privateFixedId])}},async page=>{
   const before=await page.evaluate(()=>({trips:State.trips,stored:localStorage.getItem('st_trips_v2'),storage:Object.fromEntries(Object.keys(localStorage).map(key=>[key,localStorage.getItem(key)]))}));assert.equal(before.trips.length,2);assert.equal(await page.evaluate(()=>State.trips.filter(isRetiredBuiltInTrip).length),1);await page.evaluate(()=>openLegacyDemoManager());const result=await page.evaluate(id=>{window.retiredConfirmCount=0;window.confirm=()=>{retiredConfirmCount++;return true;};return deleteRetiredBuiltInTrip(id);},retired.id);assert.equal(result,false);await page.locator(`[data-retired-delete="${retired.id}"]`).click();assert.equal(await page.evaluate(()=>retiredConfirmCount),0);assert.deepEqual(await page.evaluate(()=>State.trips),before.trips);assert.equal(await page.evaluate(()=>localStorage.getItem('st_trips_v2')),before.stored);assert.deepEqual(await page.evaluate(()=>Object.fromEntries(Object.keys(localStorage).map(key=>[key,localStorage.getItem(key)]))),before.storage);await page.reload({waitUntil:'networkidle'});assert.deepEqual(await page.evaluate(()=>State.trips),before.trips);return {duplicateIdBlocked:true,noConfirmation:true,allOriginalsPreserved:true};
  });
  assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:results.every(result=>result.passed),results,errors},null,2));assert.ok(results.every(result=>result.passed),'가상 예제 온보딩 회귀 실패');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>server.close());
