/* 사용자 데이터·외부 AI 호출 없이 지출 편집과 사진·지갑 계산을 검사한다. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'.local-review','expense-editor');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.mjs':'application/javascript','.css':'text/css'})[path.extname(file)]||'application/octet-stream');res.end(data);});});
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
try{
 const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:'networkidle'});
 await page.evaluate(()=>{window.alert=()=>{};window.confirm=()=>true;document.querySelectorAll('.sheet-container').forEach(e=>e.classList.add('sheet-closed'));State.trips=[{id:'expense-test',title:'여행 가계부',currency:'KRW',budget:500000,initialBalances:{KRW:500000,USD:100},activeCurrencies:['KRW','USD'],countries:['스페인'],cities:['마드리드'],journals:{},days:[{dayNum:1,title:'첫날',date:'2026-09-14',spots:[]}],expenses:[{id:'e1',title:'기념품 컵',curr:'KRW',amount:25000,krw:25000,date:'2026-09-14',time:'11:00',cat:'shopping',type:'expense',payMethod:'card',paymentSource:'wallet_krw',walletCurr:'KRW',photos:[],primaryPhotoIndex:0}],checklist:[]}];State.activeTripId='expense-test';saveTrips();switchView('workspace');switchTab('expenses');setTheme('modern');});
 assert.equal(await page.locator('.expense-entry img').count(),0);await page.locator('.expense-entry-open').click();
 assert.equal(await page.locator('#exp-form-amount').inputValue(),'25000');
 const preview=await page.evaluate(()=>calculateTripWallets(expensePreviewTrip()).wallets.KRW.balance);assert.equal(preview,500000);
 await page.locator('#exp-form-amount').fill('10000');
 const first=await page.evaluate(()=>({ok:submitAddExpense(),length:getActiveTrip().expenses.length,id:getActiveTrip().expenses[0].id,balance:calculateTripWallets(getActiveTrip()).wallets.KRW.balance}));assert.deepEqual(first,{ok:true,length:1,id:'e1',balance:490000});
 await page.locator('.expense-entry-open').click();
 const photoResult=await page.evaluate(async()=>{const files=[];for(const color of ['#c28a55','#366d61']){const c=document.createElement('canvas');c.width=1600;c.height=1200;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.fillRect(0,0,c.width,c.height);files.push(new File([await new Promise(r=>c.toBlob(r))],'product.png',{type:'image/png'}));}await handleExpensePhotosUpload({target:{files,value:'x'}});setPrimaryExpensePhoto(1);const before=getActiveTrip().expenses[0].krw;const saved=submitAddExpense();return {saved,before,after:getActiveTrip().expenses[0].krw,photos:getActiveTrip().expenses[0].photos.length,primary:getActiveTrip().expenses[0].primaryPhotoIndex};});
 assert.deepEqual(photoResult,{saved:true,before:10000,after:10000,photos:2,primary:1});
 assert.equal(await page.locator('.expense-entry img').count(),1);
 for(const width of [320,360,390,430]){await page.setViewportSize({width,height:844});const geometry=await page.evaluate(()=>({buttons:[...document.querySelectorAll('.expense-toolbar button')].map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})),image:[document.querySelector('.expense-entry img').width,document.querySelector('.expense-entry img').height],overflow:document.documentElement.scrollWidth>innerWidth}));assert.equal(geometry.overflow,false);assert.deepEqual(geometry.image,[56,56]);assert.equal(geometry.buttons.length,4);assert.ok(geometry.buttons.every(b=>b.h===48&&Math.abs(b.w-geometry.buttons[0].w)<1));}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'list.png'),fullPage:true});
 await page.locator('.expense-entry-open').click();await page.locator('#exp-photos-list button').first().click();assert.equal(await page.locator('#expense-photo-viewer').isVisible(),true);await page.locator('#expense-photo-viewer button').click();
 const failed=await page.evaluate(()=>{document.getElementById('exp-form-title').value='잘못 등록한 이름 수정';const old=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='st_trips_v2')throw new DOMException('quota','QuotaExceededError');return old.call(this,k,v);};let ok;try{ok=submitAddExpense();}finally{Storage.prototype.setItem=old;}return {ok,title:getActiveTrip().expenses[0].title,persisted:JSON.parse(localStorage.getItem('st_trips_v2'))[0].expenses[0].title,retry:submitAddExpense()};});assert.equal(failed.ok,false);assert.equal(failed.title,'기념품 컵');assert.equal(failed.persisted,'기념품 컵');assert.equal(failed.retry,true);
 await page.locator('.expense-entry-open').click();
 const cash=await page.evaluate(()=>{setExpensePayMethod('cash');renderExpenseCurrencyChips('USD');document.getElementById('exp-form-amount').value='10';document.getElementById('exp-form-payment-source').value='wallet_curr';submitAddExpense();const w=calculateTripWallets(getActiveTrip()).wallets;return {krw:w.KRW.balance,usd:w.USD.balance,count:getActiveTrip().expenses.length};});assert.deepEqual(cash,{krw:500000,usd:90,count:1});
 await page.locator('.expense-entry-open').click();
 const income=await page.evaluate(()=>{setExpenseTransType('income');document.getElementById('exp-form-payment-source').value='wallet_krw';submitAddExpense();const trip=getActiveTrip();return {source:trip.expenses[0].paymentSource,usd:calculateTripWallets(trip).wallets.USD.balance,krw:calculateTripWallets(trip).wallets.KRW.balance,expected:500000+trip.expenses[0].krw};});assert.equal(income.source,'wallet_krw');assert.equal(income.usd,100);assert.equal(income.krw,income.expected);
 await page.locator('.expense-entry-open').click();const conflict=await page.evaluate(()=>{getActiveTrip().expenses[0].memo='다른 화면에서 변경';return submitAddExpense();});assert.equal(conflict,false);assert.ok((await page.locator('#expense-editor-feedback').textContent()).includes('변경'));
 await page.evaluate(()=>{closeModal('modal-expense',true);openAddExpenseModal();switchExpenseModalMode('simple');});assert.equal(await page.locator('#exp-photos-list').isVisible(),true);
 await page.evaluate(()=>{ExpenseFormState.photos=['data:image/jpeg;base64,YQ=='];lastModalActionTime=0;window.confirm=()=>false;closeModal('modal-expense');});assert.equal(await page.locator('#modal-expense').evaluate(e=>e.classList.contains('sheet-closed')),false);
 await page.evaluate(()=>{window.confirm=()=>true;closeModal('modal-expense',true);openEditExpenseModal(0);});await page.screenshot({path:path.join(out,'edit.png'),fullPage:true});
 const late=await page.evaluate(async()=>{const old=compressExpensePhoto;let finish;compressExpensePhoto=()=>new Promise(r=>finish=r);const pending=handleExpensePhotosUpload({target:{files:[new File(['x'],'x.png')],value:'x'}});openAddExpenseModal();finish('data:image/jpeg;base64,YQ==');await pending;compressExpensePhoto=old;return ExpenseFormState.photos.length;});assert.equal(late,0);
 const wrongSession=await page.evaluate(()=>applyAiDraftPayload({kind:'receipt',input:{expenseSession:'old-form'}}));assert.equal(wrongSession,'conflict');
 await page.evaluate(()=>{closeModal('modal-expense',true);});await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>State.trips.find(t=>t.id==='expense-test').expenses[0].photos.length),2);
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,checks:'편집 교체/지갑 재계산, 대표사진/확대, 320~430px 버튼/썸네일, 실패 재시도, 결제수단과 수입 수정, 동시수정 충돌, 사진만 이탈방어, 재시작',errors}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
